### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kaansengul** [th3r3alandr3/rehau-nea-smart-2.0-ha#69]
## System Information

version | core-2024.10.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/Istanbul
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4976
Installed Version | 2.0.1
Stage | running
Available Repositories | 1445
Downloaded Repositories | 6

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 4
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 18, 2024 at 1:03 PM
-- | --
current_recorder_run | October 21, 2024 at 12:28 PM
estimated_db_size | 17.86 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/rehau_nea_smart_2/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I just installed and entered my username/password info then I got the error.

### Reproduction steps

1. Install via HACS
2. Enter login info

### Debug logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 12:30:23 PM (3 occurrences)
Last logged: 12:31:44 PM

Error setting up entry REHAU Nea Smart 2.0 API for rehau_nea_smart_2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rehau_nea_smart_2/__init__.py", line 27, in async_setup_entry
    await controller.connect()
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/Controller.py", line 33, in connect
    await self.mqtt_client.auth_user()
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/MqttClient.py", line 310, in auth_user
    await self.set_user(user)
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/MqttClient.py", line 388, in set_user
    await self.set_installations(user["installs"])
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/MqttClient.py", line 332, in set_installations
    await self.update_installations(installations)
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/MqttClient.py", line 338, in update_installations
    self.installations = parse_installations(installations, self.last_operating_mode)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/handlers/installation.py", line 27, in parse_installations
    "global_energy_level": get_global_energy_level(installation).value,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/utils/energy_levels.py", line 22, in get_global_energy_level
    for group in installation["groups"]:
                 ~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'groups'
```

### Diagnostics dump

[config_entry-hacs-01JAFZXXNQNHT36EDDBPBDB10F.json](https://github.com/user-attachments/files/17458665/config_entry-hacs-01JAFZXXNQNHT36EDDBPBDB10F.json)

**Comment by Mihao82** [comment]
I have the same issue

**Comment by grinzy2003-lgtm** [comment]
Also the same Issue
