### ISSUE TITLE
Adding real time data

### ISSUE THREAD

**Issue by pakozack** [th3r3alandr3/rehau-nea-smart-2.0-ha#70]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/rehau_nea_smart_2/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm trying to read real_time data from mqtt. After adding type "live_data" in handle_user_message method I can read value of pumpOn, mixed_circuit1_setpoint, mixed_circuit1_supply, mixed_circuit1_return and mixed_circuit1_opening.
Now I need to request refresh of this data. How can I do? Wich message I must send?

### Describe the solution you'd like

![IMG_6BBA40E2D2B9-1](https://github.com/user-attachments/assets/5e9f3dde-37ca-442a-928d-fcae53481308)

### Describe alternatives you've considered

Simulate action of app "Premere per aggiornare"

### Additional context

none

**Comment by th3r3alandr3** [comment]
I'm not entirely sure what your ultimate goal is with refreshing the MQTT data. 

If you're trying to display these live_data values within Home Assistant, the best approach is to create corresponding Home Assistant entities, such as sensors. You shouldn't need to manually "request a refresh".

**Comment by pakozack** [comment]
Hi, I discovered message to send via mqqt to receive live data. 
The code seems like

        payload = { "11": "REQ_LIVE", "12": { "DATA": "1" } }
        self.send_message(ClientTopics.INSTALLATION.value, payload)

Now I receive message for type "live_data", and I can read values I need.
In my fork I have added humidity sensors, binary sensor for pump on, digital output and digital input, supply and return temperature.
I'm not expert in HA. Any suggestions are welcome.

**Comment by crisking** [comment]
Hello, 

Are you still developing this fork? 
It could be very interesting

**Comment by pakozack** [comment]
Hi @crisking,
I paused development after a Rea Smart update released in March.
Since this update, I've no longer been able to receive the real-time data used to update flow temperature, return temperature, etc.

You can view my fork here
https://github.com/pakozack/rehau-nea-smart-2.0-ha
and if you want to help me out :D

**Comment by crisking** [comment]
They should have changed something also one week ago approximately. 
I cannot access anymore by my account in Home assistant, I noted it only this morning

Despite it is working fine on Rehau app.

**Comment by latecka** [comment]
> They should have changed something also one week ago approximately. I cannot access anymore by my account in Home assistant, I noted it only this morning
> 
> Despite it is working fine on Rehau app.

I have a similar problem. The integration has basically stopped working. Error message:


Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 11:52:28 (1 occurrence)
Last logged: 11:52:28

Error setting up entry REHAU Nea Smart 2.0 API for rehau_nea_smart_2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rehau_nea_smart_2/__init__.py", line 27, in async_setup_entry
    await controller.connect()
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/Controller.py", line 33, in connect
    await self.mqtt_client.auth_user()
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/MqttClient.py", line 308, in auth_user
    token_data, user = await auth(self.auth_username, self.auth_password)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/rehau_nea_smart_2/rehau_mqtt_client/handlers/auth.py", line 96, in auth
    raise MqttClientAuthenticationError("Could not get user data")
custom_components.rehau_nea_smart_2.rehau_mqtt_client.exceptions.mqtt_client_exceptions.MqttClientAuthenticationError: Could not get user data

**Comment by crisking** [comment]
Any solution in the meantime? 

At the moment I tried something, but without success.

Still blocked by same error message as @latecka
